name: CI/CD Pipeline with Docker and EC2 (No Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker en GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker localmente
      - name: Build Docker image
        run: |
          docker build -t my-calculator-app .

      # 4. Copiar la imagen Docker a la instancia EC2 usando SSH y SCP
      - name: Copy Docker image to EC2
        run: |
          docker save my-calculator-app | ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} 'docker load'

      # 5. Desplegar la aplicación en EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker stop my-calculator-app || true
            docker rm my-calculator-app || true
            docker run -d -p 80:80 --name my-calculator-app my-calculator-app
          EOF
