name: CI/CD Pipeline with Docker and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker en GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker localmente
      - name: Build Docker image
        run: |
          docker build -t my-calculator-app .

      # 4. Guardar la imagen Docker como archivo tar y transferirlo a EC2
      - name: Save and Copy Docker image to EC2
        run: |
          # Guardar la imagen Docker como un archivo tar
          docker save my-calculator-app -o my-calculator-app.tar

          # Guardar la clave privada en un archivo temporal
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Copiar el archivo TAR de la imagen Docker a EC2 usando SCP
          scp -o StrictHostKeyChecking=no -i private_key.pem my-calculator-app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }}:/home/${{ secrets.EC2_USER }}/

          # Eliminar la clave privada después de usarla
          rm -f private_key.pem

      # 5. Instalar Docker en EC2 si no está instalado y cargar la imagen Docker
      - name: Install Docker and Load Docker image on EC2
        run: |
          # Guardar la clave privada en un archivo temporal
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Conectarse a la instancia EC2 e instalar Docker si es necesario
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Verificar si Docker está instalado
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
              newgrp docker  # Aplicar cambios de grupo en la sesión actual
            fi

            # Cargar la imagen Docker desde el archivo TAR
            docker load < /home/${{ secrets.EC2_USER }}/my-calculator-app.tar
            # Detener y eliminar contenedores anteriores
            docker stop my-calculator-app || true
            docker rm my-calculator-app || true
          EOF

          # Eliminar la clave privada después de usarla
          rm -f private_key.pem

      # 6. Desplegar la aplicación en EC2
      - name: Deploy to EC2
        run: |
          # Guardar la clave privada en un archivo temporal
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Ejecutar el contenedor en EC2
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker run -d -p 80:80 --name my-calculator-app my-calculator-app
          EOF

          # Eliminar la clave privada después de usarla
          rm -f private_key.pem
