name: CI/CD Pipeline with Docker and EC2 (No Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker en GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker localmente
      - name: Build Docker image
        run: |
          docker build -t my-calculator-app .
          docker images  # Verifica que la imagen fue construida

      # 4. Guardar la imagen y transferirla a EC2
      - name: Save and transfer Docker image to EC2
        run: |
          docker save my-calculator-app | gzip > my-calculator-app.tar.gz
          scp -i ${{ secrets.EC2_SSH_KEY }} my-calculator-app.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

      # 5. Cargar la imagen Docker en la instancia EC2
      - name: Load Docker image on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            gzip -d /tmp/my-calculator-app.tar.gz
            sudo docker load < /tmp/my-calculator-app.tar

      # 6. Verificar que la imagen fue cargada en EC2
      - name: Verify Docker image on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo docker images

      # 7. Desplegar la aplicación en EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop my-calculator-app || true
            sudo docker rm my-calculator-app || true
            sudo docker run -d -p 80:80 --name my-calculator-app my-calculator-app
