name: CI/CD Pipeline with Docker

# Trigger el workflow en push a la rama main
on:
  push:
    branches:
      - main  # se ejecuta cuando se hace un push a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Ejecuta en un entorno Ubuntu

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Iniciar sesión en Docker Hub (si vas a subirlo a Docker Hub)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 4: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t my-calculator-app .