name: CI/CD Pipeline with Docker and EC2 (No Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker en GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker localmente
      - name: Build Docker image
        run: |
          docker build -t my-calculator-app .

      # 4. Copiar la imagen Docker a EC2 y cargarla usando SSH (appleboy/ssh-action)
      - name: Copy Docker image to EC2 and load
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker save my-calculator-app | docker load

      # 5. Desplegar la aplicación en EC2 usando SSH (appleboy/ssh-action)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop my-calculator-app || true
            sudo docker rm my-calculator-app || true
            sudo docker run -d -p 80:80 --name my-calculator-app my-calculator-app
