name: CI/CD Pipeline with Docker and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker en GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Construir la imagen Docker localmente
      - name: Build Docker image
        run: |
          docker build -t my-calculator-app .

      # 4. Copiar la imagen Docker a la instancia EC2 usando SSH
      - name: Copy Docker image to EC2
        run: |
          # Guardar la clave privada en un archivo temporal
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # Verificar que la clave se haya guardado correctamente (opcional, puedes eliminar esto en producción)
          # cat private_key.pem

          # Copiar la imagen Docker a EC2 y cargarla allí
          docker save my-calculator-app | ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} 'docker load'

          # Eliminar la clave privada después de usarla
          rm -f private_key.pem

      # 5. Instalar Docker (si es necesario) y desplegar la aplicación en EC2
      - name: Deploy to EC2
        run: |
          # Guardar la clave privada en un archivo temporal
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # Conectarse a EC2 para instalar Docker si es necesario
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Instalar Docker si no está instalado
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
              newgrp docker  # Aplicar cambios de grupo en la sesión actual
            fi
            
            # Detener y eliminar contenedores anteriores
            docker stop my-calculator-app || true
            docker rm my-calculator-app || true
            
            # Ejecutar el contenedor
            docker run -d -p 80:80 --name my-calculator-app my-calculator-app
          EOF

          # Eliminar la clave privada después de usarla
          rm -f private_key.pem
